source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'AgilePoker' do
    
    use_frameworks!

	#External pods
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftLint'
    
end

